name: Run tests in a Matrix
on:
  workflow_dispatch:

env:
  CYPRESS_USERNAME: ${{ secrets.CYPRESS_USERNAME }}
  CYPRESS_PASSWORD: ${{ secrets.CYPRESS_PASSWORD }}

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        browser: [electron, edge, chrome]
        platform: [ubuntu-latest, macos-latest, windows-latest]
        exclude:
          - platform: windows-latest
            browser: electron
          - platform: ubuntu-latest
            browser: edge
          - platform: macos-latest
            browser: electron
          - platform: macos-latest
            browser: edge
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v6
    - run: npm ci
    - name: Running on Platform = ${{ matrix.platform }} Browser = ${{ matrix.browser }}
      run: npx cypress run --browser ${{ matrix.browser }}